import "./globals.css";
import { Roboto_Flex } from "next/font/google";
import Navbar from "./navbar";
import UserProvider from "./AppContext";

const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "NĀMAKA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={robotoFlex.className}>
      <body className="min-h-screen">
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
